account_id = "e184d4860c8f69f9fa10e3fe7e3e57e6"
compatibility_date = "2021-10-23"
name = "www-dev"
type = "webpack"
workers_dev = true
zone_id = "cad1b7d6692e05575473df968f1b1280"

[site]
bucket = "out"
entry-point = "src/cfworker"

[env.production]
name = "www-prod"
route = "trilogymp.com/*"
